### PR TITLE
Bring zf3 support

### PR DESCRIPTION
**Pull request by basz**

### CODE REVIEW

**Comment by basz** [comment]
@Danielss89 I see the tests aren't running. Is that something you can fix?

**Comment by Danielss89** [comment]
Hm, as this is not an organization, i actually can't do anything on travis :/
So @juriansluiman will have to get the tests going again.
I think it happened when the repo was moved from the Soflomo organization to Jurians private account.

**Comment by basz** [comment]
That ok. Im using the fork atm. Actually forgot i did a stil open PR

**Comment by Danielss89** [comment]
Ok, basz, so this is actually working?
I can merge?

**Comment by basz** [comment]
yes it works. Please do if you can, I thought it was abandoned as jurian has moved on to other things

**Comment by basz** [comment]
Configuration: /Users/bas/Sandbox/Soflomo-Mail/phpunit.xml

................................................                  48 / 48 (100%)

Time: 1.46 seconds, Memory: 10.00MB

OK (48 tests, 112 assertions)

**Comment by Danielss89** [comment]
Any breaking changes?
man. 6. mar. 2017 kl. 22.50 skrev Bas Kamer <notifications@github.com>:

**Comment by basz** [comment]
hmm. no more php5.3 min php56

think that's it

**Comment by Danielss89** [comment]
I will tag new release later today

**Comment by basz** [comment]
hm, it seems https://packagist.org/packages/soflomo/mail isn't updating either... that's problematic

**Pull request merged**
